### PR TITLE
Fix C flags to allow cross-compilation

### PR DESCRIPTION
**Pull request by samoht**
/cc @dinosaure and @avsm (who helped me debugging the issue)

### CODE REVIEW

**Comment by dinosaure** [comment]
Currenlty with `dune.2.4.0`, `:standard` puts `-O2 -fno-strict-aliasing -fwrapv -fPIC`, you can check it with:
```sh
$ dune printenv
```

**Comment by hannesm** [comment]
thanks, as noted in #46 please let us wait until I conducted some experiments before merging. thanks.

**Comment by hannesm** [comment]
should the same `(:standard)` be added in the `freestanding` and `xen` subdirectories? would be good to keep them in sync.

**Comment by hannesm** [comment]
thanks

**Pull request merged**
