### PR TITLE
github actions: actually build the code and execute the tests

### PR DESCRIPTION
**Pull request by hannesm**
//cc @avsm @smorimoto to me it looks like the github actions do not compile the code and run the tests at the moment!?

### CODE REVIEW

**Comment by hannesm** [comment]
Hmm, unfortuately I don't quite understand `setup-ocaml`, and now when re-adding the package names to `windows.yml`, suddenly all these CI jobs fail with `bad hash` -- any clue whether this is a temporary issue, or are the windows CI systems in a desolate state? //cc @smorimoto

**Comment by avsm** [comment]
Not sure what's wrong here -- looks like a bug in setup-ocaml.

**Comment by hannesm** [comment]
I restarted the GitHub actions, and the windows compilation succeeds now.

@EduardoRFS would you be able to take a look into the cross-compilation CI and why it is failing? it complains about missing dune-configurator, but I've no clue where to adjust that... also, mirage-crypto opam file has a dependency onto dune-configuratior.

**Comment by EduardoRFS** [comment]
@hannesm feel free to remove it, I don't have time anymore to maintain it, I apologize for the stress

**Comment by hannesm** [comment]
@EduardoRFS ok, thanks.

**Pull request merged**
