### PR TITLE
misc: detect CPU architecture from C compiler

### PR DESCRIPTION
**Pull request by EduardoRFS**
This allows to cross-compile from x86_64 -> ARM64.

### CODE REVIEW

**Comment by hannesm** [comment]
this looks fine to me (travis failure is unrelated).. do you know of a CI setup to test cross-compilation (to ensure we don't break it in the future)?

**Comment by rizo** [comment]
I can confirm that this patch resolves the issue. We have a private cross-compiling CI that targets ARM and uses some mirage packages, would be nice to make it available for open-source projects at some point.

**Comment by EduardoRFS** [comment]
@hannesm My tooling uses esy for that, if you don't mind I can setup a CI to build for Android ARM64

**Comment by hannesm** [comment]
@EduardoRFS if you can add a commit here that extends e.g. the GitHub actions (or travis) with such a job, that'd be great. Thanks a lot.

**Comment by hannesm** [comment]
@EduardoRFS thanks for your second commit, somehow the CI job fails to find ndk.zip - is it expected to work, should I restart the action, or do you have an adjustment to the runner for this?

**Comment by EduardoRFS** [comment]
@hannesm I'm debugging it, it's something related to the shell used on the CI, I should finish it today

**Comment by hannesm** [comment]
@EduardoRFS great, thanks. if you rebase onto master, the travis CI should also turn green.

**Comment by EduardoRFS** [comment]
Ok now it should work

## Dependencies

All dependencies are extracted from opam and every commit `esy solve` will look for a new version, if no dependency changed it will keep cached.

Except, `mtime` has a pinned commit to dune-universe. Because to build to another platform is way easier to just use the dune version

## Missing

Only the `mirage-crypto-pk` is missing, as it depends on `gmp` and I didn't figure it out a way to build it for Android.

**Comment by EduardoRFS** [comment]
@hannesm sorry for all the CI noise. Zarith and GMP was a small problem and there was also an intermittent compile bug(solved)

**Comment by hannesm** [comment]
@EduardoRFS thanks for your work on this, one minor nit: could you squash the last 3 commits (CI-related) into one. then this is fine to be merged. I can also do a release to opam-repository if this eases your workflow.

**Review by hannesm — APPROVED** [review]

**Pull request merged**
