### PR TITLE
adapt to mirage-unix 5.0.0

### PR DESCRIPTION
**Pull request by hannesm**
//cc @dinosaure

### CODE REVIEW

**Comment by hannesm** [comment]
this results in ocaml-ci being stuck that mirage-runtime > 4.0 is now in the (test) dependency chain which is only available in opam-version >= 2.1. //cc @talex5 any chance we can get ocaml-ci with opam 2.1?

**Comment by talex5** [comment]
@samoht merged a PR that was supposed to fix that: https://github.com/ocurrent/ocaml-ci/pull/413

**Comment by dinosaure** [comment]
For me it's perfect. We don't need a release of the distribution when the `mirage-unix` is bring only by testing.

**Comment by hannesm** [comment]
@talex5 @samoht thanks, so but according to the CI log this has not been fixed... maybe it makes a difference between an opam file with availability vs a transitive dependency that has this availability?

**Comment by talex5** [comment]
I think it's just a bug parsing the string: https://github.com/ocurrent/ocaml-ci/issues/412#issuecomment-1029128460

**Comment by hannesm** [comment]
thanks to everyone involved, the ocaml-ci seems to be successful now (also on non-amd64 architectures).

**Pull request merged**
