### PR TITLE
Require ounit2 instead of ounit

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by hannesm** [comment]
thanks, the CI discovered:
```
File "tests/dune", line 9, characters 38-43:
9 |  (libraries test_common mirage-crypto oUnit)
                                          ^^^^^
Error: Library "oUnit" not found.
```

so, there are several occurences of `oUnit` in dune that should use `oUnit2` now.

**Comment by MisterDA** [comment]
I had grepped for `ounit` instead of `oUnit`.

**Comment by hannesm** [comment]
thanks. @EduardoRFS would you mind to take a look into the esy/cross-build failures:
```
  info installing: done
Error: reserveCache failed: Cache already exists. Scope: refs/pull/149/merge, Key: source-darwin-macos.arm64-98ee46ba14ff10ab8aae0241312dd62fbdf8e22f9cccd4708f1dae0ccbac68c5, Version: 0e0a857b757f8fcf249f45fb68dd35c72534a4f623eaaef730a1cb88d583cfcf
```

thanks. waiting for the remaining CI before merge.

**Comment by EduardoRFS** [comment]
@hannesm I think this one was just a conflict of cache, seems like on main it has already been fixed.

**Pull request merged**
